spring:
  datasource:
    url: jdbc:mysql://localhost:3306/customerdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: customerapp
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    user: customeradmin
    password: password
  profiles:
    active: local, clean
logging:
  file:
    name: logs/local/customer.log
